version: "3.3"
services:
  collector:
    image: workingstats/collector:latest
    container_name: stats-collector
    ports:
      - "8180:8080"
    volumes:
      - /home/dev/stats/logs/collector:/var/log/stats